export const CARGAR_USUARIOS = "CARGAR_USUARIOS";
export const SEGUIR_CUENTA = "SEGUIR_CUENTA";
export const ELIMINAR_SEGUIDO = "ELIMINAR_SEGUIDO";
export const CARGAR_SEGUIDOS = "CARGAR_SEGUIDOS";

export const CARGAR_RUTAS = "CARGAR_RUTAS";
export const CREAR_RUTA = "CREAR_RUTA";
export const CREAR_COORDENADA = "CREAR_COORDENADA";
export const GUARDAR_COORDENADAS = "GUARDAR_COORDENADAS";
export const ASIGNAR_PARTICIPANTES = "ASIGNAR_PARTICIPANTES";
export const CARGAR_RUTAS_DE_PARTICIPANTES = "CARGAR_RUTAS_DE_PARTICIPANTES";
export const DEJAR_DE_PARTICIPAR = "DEJAR_DE_PARTICIPAR";
